# Generated by Django 4.2.30 on 2026-08-10 03:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('waktu', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kehadiran.siswa')),
            ],
        ),
    ]
