# Generated by Django 4.2.30 on 2026-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0002_absensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='no_hp_ortu',
            field=models.CharField(default='', help_text='Nomor WA Orang Tua, contoh: 628xxxxxxxxxx', max_length=15),
            preserve_default=False,
        ),
    ]
