# Generated by Django 4.2.30 on 2026-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0003_siswa_no_hp_ortu'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='jam_pulang',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='absensi',
            unique_together={('siswa', 'tanggal')},
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='waktu',
        ),
    ]
